package cooper.ui;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;

/**
 * Represents a dialog box consisting of an ImageView to represent the speaker's face
 * and a label containing text from the speaker.
 */
public class DialogBox extends HBox {

    @FXML
    private Label dialog;

    @FXML
    private ImageView displayPicture;

    private DialogBox(String text, Image img) {
        try {
            // Resolve the resource relative to the control that owns it to keep the relationship explicit.
            FXMLLoader fxmlLoader = new FXMLLoader(DialogBox.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException e) {
            // A partially initialized dialog would fail later with a less informative null-pointer error.
            throw new IllegalStateException("Unable to load the dialog box", e);
        }

        dialog.setText(text);
        displayPicture.setImage(img);
    }

    /**
     * Flips the dialog box so that Cooper's image is on the left and text is on the right.
     */
    private void flip() {
        ObservableList<Node> tmp = FXCollections.observableArrayList(this.getChildren());
        Collections.reverse(tmp);
        getChildren().setAll(tmp);
        setAlignment(Pos.TOP_LEFT);
        dialog.getStyleClass().add("reply-label");
    }

    /**
     * Creates a right-aligned dialog for user input.
     *
     * @param text Text entered by the user.
     * @param img User display image.
     * @return User dialog box.
     */
    public static DialogBox getUserDialog(String text, Image img) {
        return new DialogBox(text, img);
    }

    /**
     * Creates a left-aligned dialog for Cooper's response.
     *
     * @param text Response generated by Cooper.
     * @param img Cooper display image.
     * @return Cooper dialog box.
     */
    public static DialogBox getCooperDialog(String text, Image img) {
        return getCooperDialog(text, img, false);
    }

    /**
     * Creates a reply with a visible error heading and styling when the command failed.
     * The heading belongs only to the GUI; the original response remains suitable for the CLI.
     *
     * @param text Response generated by Cooper.
     * @param img Cooper display image.
     * @param isError Whether the command failed.
     * @return Cooper dialog box.
     */
    public static DialogBox getCooperDialog(String text, Image img, boolean isError) {
        var db = new DialogBox(isError ? "Error\n" + text : text, img);
        db.flip();
        if (isError) {
            db.dialog.getStyleClass().add("error-label");
        }
        return db;
    }
}
